export enum ErrorCode {
    E1000 = "this is not a POST request.",
    E1001 = "this is not an Authorization (api) key.",
    E1002 = "Your Authorization (api) key is not valid (can be expired or removed).",
    E1003 = "Request limit reached. Upgrade your API plan.",
    E1004 = "Provided API request is not available.",
    E1005 = "You didn\'t gave us an username.",
    E1006 = "You didn\'t gave us an real username.",
    E1007 = "You didn\'t gave us an user id.",
    E1008 = "You didn\'t gave us a platform. Platforms are xb1, ps4 and pc.",
    E1009 = "You gave a non-existing platform. Platforms are xb1, ps4 and pc.",
    E1010 = "You didn\'t gave us a language.",
    E1011 = "You gave us a non-existing language.",
    E1012 = "this user does not exist or didn\'t play Fortnite.",
    E1013 = "Please enter a platform (pc, ps4 or xb1).",
    E1014 = "Please enter a gamemode (solo, duo or squad).",
    E1015 = "Please enter a correct window (top_1_wins, top_10_kills, top_10_wins, top_10_score).",
    E1016 = "Leaderboard is unavailable right now.",
}