export enum ErrorCode {
    E1000 = <any>'this is not a POST request.',
    E1001 = <any>'this is not an Authorization (api) key.',
    E1002 = <any>'Your Authorization (api) key is not valid (can be expired or removed).',
    E1003 = <any>'Request limit reached. Upgrade your API plan.',
    E1004 = <any>'Provided API request is not available.',
    E1005 = <any>'You didn\'t gave us an username.',
    E1006 = <any>'You didn\'t gave us an real username.',
    E1007 = <any>'You didn\'t gave us an user id.',
    E1008 = <any>'You didn\'t gave us a platform. Platforms are xb1, ps4 and pc.',
    E1009 = <any>'You gave a non-existing platform. Platforms are xb1, ps4 and pc.',
    E1010 = <any>'You didn\'t gave us a language.',
    E1011 = <any>'You gave us a non-existing language.',
    E1012 = <any>'this user does not exist or didn\'t play Fortnite.',
    E1013 = <any>'Please enter a platform (pc, ps4 or xb1).',
    E1014 = <any>'Please enter a gamemode (solo, duo or squad).',
    E1015 = <any>'Please enter a correct window (top_1_wins, top_10_kills, top_10_wins, top_10_score).',
    E1016 = <any>'Leaderboard is unavailable right now.',
}